---
user: "{{ ansible_user_id }}"              # your user
group: "{{ user }}"                        # your user's primary group
home_dir: "/home/{{ user }}"               # your user's homedir
projects_dir: "{{ home_dir }}/projects"         # folder with your (git) projects
local_soft_dir: "{{ home_dir }}/software"  # where to save local installations of software (webstorm, pycharm etc.)
temp_dir: /tmp                             # temporary dir for downoaded files

software:
  nodejs:
    version: "6.x"
    config_prefix: "{{ home_dir }}/.npm-global/"   # directory for global installations, so it does not require sudo to install
  webstorm:
    version: "WebStorm-2016.3.3"
  intellij:
    version: "ideaIC-2016.3.4"
  pycharm:
    version: "pycharm-community-2016.3.3"
  docker_compose:
    version: "1.9.0"
  kubernetes:
    minikube:
      version: "v0.15.0"
    kops:
      version: "v1.4.4"
  peek:
    url: "https://github.com/phw/peek/releases/download/v0.8.0/peek-0.8.0-Linux.deb"
  vagrant:
    url: "https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb"
  virtualbox:
    url: "https://download.virtualbox.org/virtualbox/5.1.12/virtualbox-5.1_5.1.12-112440~Ubuntu~xenial_amd64.deb"
