---
user: '{{ ansible_user_id }}'              # your user
group: '{{ user }}'                        # your user's primary group
home_dir: '/home/{{ user }}'               # your user's homedir
projects_dir: '{{ home_dir }}/projects'    # folder with your (git) projects
local_soft_dir: '{{ home_dir }}/software'  # where to save local installations of software (webstorm, pycharm etc.)
temp_dir: /tmp                             # temporary dir for downoaded files

virtualenv:
  envs_dir: '{{ home_dir }}/envs'

software:
  docker_compose:
    version: '1.16.1'
  gogland:
    version: 'gogland-172.3757.46'
  gradle:
    version: '4.2.1'
  intellij:
    version: 'ideaIC-2017.2.5'
  kubernetes:
    minikube:
      url: 'https://storage.googleapis.com/minikube/releases/v0.18.0/minikube-linux-amd64'
    kops:
      url: 'https://github.com/kubernetes/kops/releases/download/1.5.3/kops-linux-amd64'
  nodejs:
    config_prefix: '{{ home_dir }}/.npm-global/'   # directory for global installations, so it does not require sudo to install
  pycharm:
    version: 'pycharm-community-2017.1.5'
  terraform:
    url: 'https://releases.hashicorp.com/terraform/0.10.2/terraform_0.10.2_linux_amd64.zip'
  vagrant:
    url: 'https://releases.hashicorp.com/vagrant/1.9.7/vagrant_1.9.7_x86_64.rpm'
  virtualbox:
    version: 'VirtualBox-5.1'
  webstorm:
    version: 'WebStorm-2017.2.4'
