---
user: '{{ ansible_user_id }}'
group: '{{ user }}'
home: "{{ '/home' if ansible_os_family == 'RedHat' else'/Users' }}" # fedora or mac
home_dir: '{{ home }}/{{ user }}'
projects_dir: '{{ home_dir }}/projects'
local_soft_dir: '{{ home_dir }}/software'
temp_dir: '/tmp'

virtualenv:
  envs_dir: '{{ home_dir }}/envs'

software:
  kubernetes:
    minikube:
      url: 'https://storage.googleapis.com/minikube/releases/v0.18.0/minikube-linux-amd64'
    kops:
      url: 'https://github.com/kubernetes/kops/releases/download/1.5.3/kops-linux-amd64'
  nodejs:
    config_prefix: '{{ home_dir }}/.npm-global/'
  virtualbox:
    version: 'VirtualBox-5.2'
