---
# https://docs.snapcraft.io/installing-snap-on-fedora/6755
- name: snap is present
  dnf:
    name: snapd
    state: latest
  become: yes


- name: symlink for classic snap support is created
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    mode: 0644
    force: yes
  become: yes
