---
- name: Rpm fusion repo is added
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm"
    state: present
  become: yes

- name: Vlc is present
  dnf:
    name: vlc
    state: latest
  become: yes