# Start: `gnome-tweak-tools -v` then check terminal output for values
---
- name: power button action does nothing
  shell: gsettings set org.gnome.settings-daemon.plugins.power power-button-action nothing

# you will need to reboot for this to take effect
- name: lid switch and suspend key does nothing
  lineinfile:
    dest: /etc/systemd/logind.conf
    regexp: '{{item.setting}}'
    line: '{{item.setting}}={{item.value}}'
  with_items:
    - { setting: HandleSuspendKey, value: ignore }
    - { setting: HandleLidSwitch, value: lock }
    - { setting: HandlePowerKey, value: ignore }
  become: yes
