---
- name: set install dir
  set_fact:
    install_dir: '{{ local_soft_dir }}/{{ software_name }}/{{ software_version }}'

- name: 'check current {{ software_version }} installation'
  stat:
    path: '{{ install_dir }}'
  register: already_exists

- block:
  - name: '{{ software_name }} tar is present'
    get_url:
      dest: '{{ temp_dir }}/{{ software_version }}.tar.gz'
      url: '{{ software_url }}'

  - name: '{{ software_name }} folder is present'
    file:
      path: '{{ install_dir }}'
      state: directory

  - name: '{{ software_name }} archive is unarchived'
    unarchive:
      src: '{{ temp_dir }}/{{ software_version }}.tar.gz'
      dest: '{{ install_dir }}/'

  - name: find extracted folder name
    find:
      paths: '{{ install_dir }}'
      file_type: directory
      recurse: no
    register: extracted_content

  - name: set exact install dir
    set_fact:
      exact_install_dir: '{{ extracted_content.files[0].path }}'

  - name: create symlink in /usr/local/bin
    file:
      src: '{{ exact_install_dir }}/bin/{{ software_name }}.sh'
      dest: '/usr/local/bin/{{ software_name }}'
      state: link
      mode: 0644
      force: yes
    become: yes

  when: already_exists.stat.exists == false


