---
- name: Get Fedora version
  shell: "rpm -E %fedora"
  register: version

- name: Rpm fusion free repo is present
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ version.stdout }}.noarch.rpm"
    state: present
  become: yes

- name: Rpm fusion nonfree is present
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ version.stdout }}.noarch.rpm"
    state: present
  become: yes