---
- name: installs my many software
  gather_facts: yes
  hosts: local

  roles:
    - facts
    - ping
    - remove_folders
    - bookmarks
    - vim
    - lastpass
    - red_root
    - mc
    - keybindings
    - caps_to_escape
    - show_minimize_button
    - enable_fedora_extensions
    - disable_suspend_on_lid_close
    - top_bar_show_date
    - hstr
    - ack
    - htop
    - unzip
    - yubikey_personalization_gui
    - jq
    - tmux
    - iftop
    - ncdu
    - virtualenv
    - pygmentize
    - wallpaper
    - gnome_tweak_tools
    - arc_icons
    - powerline_fonts
    - terminal_config
    - tilix
    - nodejs
    - nvm
    - oh_my_zsh
    - fuzzy_project_finder
    - yarn
    - gr
    - aws_cli
    - aws_shell
    - gitk
    - docker
    - docker_compose
    - gpick
    - peek
    - fuse_exfat
    - terraform
    - sdkman
    - sdkman_packages
    - idea
      #- webstorm
      #- pycharm
      #- goland
      #- rider
      #- datagrip
      #- rubymine
    - gimp
      #- atom
      #- vsc
      #- vagrant
      #- virtualbox
    - slack
    - spotify
    - vlc
