---
- name: pycharm is present
  include_role:
    name: generic_jetbrains
  vars:
    software_human_name: 'PyCharm'
    software_name: 'pycharm'
    software_config_dir: '{{ software.pycharm.config_dir }}'
    software_version: '{{ software.pycharm.version }}'
    software_url: 'https://download.jetbrains.com/python/{{ software.pycharm.version }}.tar.gz'