---
- name: pycharm is present
  include_role:
    name: generic_jetbrains
  vars:
    software_name: 'pycharm'
    software_version: '{{ software.pycharm.version }}'
    software_url: 'https://download.jetbrains.com/python/{{ software.pycharm.version }}.tar.gz'