---
- name: my wallpaper is present
  get_url:
    url: 'https://i.imgur.com/RWQKEw5.jpg'
    dest: '{{ temp_dir }}/wallpaper.jpg'

# we could use `dconf dump / | grep -C 5 "/desktop/"`
# cat /usr/share/backgrounds/f27/default/f27.xml
- name: default wallpaper is overwritten with my own
  copy:
    src: '{{ temp_dir }}/wallpaper.png'
    dest: '{{ item }}'
  with_items:
    - '/usr/share/backgrounds/f27/default/tv-wide/f27.jpg'
    - '/usr/share/backgrounds/f27/default/wide/f27.jpg'
  become: yes
