---
- name: oh-my-zsh repo is cloned
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: '{{home_dir}}/.oh-my-zsh'
    depth: 1

- name: zsh is installed
  dnf:
    name: zsh
    state: latest
  become: yes

- name: set zsh as default shell
  command: usermod -s /usr/bin/zsh {{ user }}
  become: yes

- name: bullet-train theme is present
  get_url:
    url: 'http://raw.github.com/caiogondim/bullet-train-oh-my-zsh-theme/master/bullet-train.zsh-theme'
    dest: '{{ home_dir }}/.oh-my-zsh/custom/themes/bullet-train.zsh-theme'