---
- name: Download nodejs official setup script
  get_url: >
    url="https://deb.nodesource.com/setup_{{ software.nodejs.version }}"
    dest={{ temp_dir }}/nodejs_setup_{{ software.nodejs.version }}.sh
    mode=0777
    validate_certs=no

- block:
  - name: Install apt-transport-https
    apt: >
      name=apt-transport-https
      state=present

  - name: Run nodejs official setup script
    script: "{{ temp_dir }}/nodejs_setup_{{ software.nodejs.version }}.sh"

  - name: Install nodejs
    apt: >
      name=nodejs={{ software.nodejs.version|regex_replace('x', '') }}*
      state=present

  - name: Install build-essentials
    apt: >
      name=build-essential
      state=present

  - name: Set npm global modules installation folder to home so it doesn't require sudo
    command: npm config set prefix {{ software.nodejs.config_prefix }} --global

  - name: Force saving exact versions
    command: npm config set save-exact=true

  become: yes

