---
- name: Nodejs and npm is present
  dnf:
    name: nodejs
    state: latest
  become: yes

- name: Set npm global save directory
  command: npm config set prefix {{ software.nodejs.config_prefix }} --global
  become: yes

- name: Force saving exact versions
  command: npm config set save-exact=true