---
- name: node and npm is present [fedora]
  dnf:
    name: nodejs
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'

- name: node and npm is present [macos]
  homebrew:
    name: nodejs
    state: latest
  when: ansible_os_family == 'Darwin'

- name: set npm global save directory
  command: npm config set prefix {{ software.nodejs.config_prefix }} --global
  become: yes

- name: force saving exact versions
  command: npm config set save-exact=true