---
# Subset of Moka icons can be used by Arc icons
- name: Moka icon set repo is added
  apt_repository:
    repo: 'ppa:moka/daily'
    update_cache: yes
  become: yes

- name: Moka icon set is installed
  apt:
    name: moka-icon-theme
    state: latest
  become: yes

