---
- name: my home repo is cloned
  git:
    repo: git@github.com:hoto/home.git
    accept_hostkey: yes
    update: yes
    dest: "{{ projects_dir }}/hoto/home"

- name: folders for my configs are present
  file:
    path: "{{ home_dir }}/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - .atom
    - .bash
    - .bash/git-aware-prompt
    - .config
    - .config/autostart
    - .config/Code/User
    - .config/terminix
    - .config/terminix/schemes
    - .vim/plugin
    - .vim/snippets

- name: symlinks to my configs are present
  file:
    src: "{{ projects_dir }}/hoto/home/{{ item }}"
    dest: "{{ home_dir }}/{{ item }}"
    state: link
    mode: 0644
    force: yes
  with_items:
    - .ackrc
    - .atom/config.cson
    - .atom/keymap.cson
    - .bash/256colors2.pl
    - .bash/colortest.py
    - .bash/git-aware-prompt/colors.sh
    - .bash/git-aware-prompt/main.sh
    - .bash/git-aware-prompt/prompt.sh
    - .bash/ps1.sh
    - .bashrc
    - .config/Code/User/settings.json
    - .config/autostart/ignore-lid-switch-tweak.desktop
    - .config/autostart/setxkbmap.desktop
    - .config/terminix/schemes/terminix-dark.json
    - .gitattributes
    - .gitconfig
    - .gitignore_global
    - .ideavimrc
    - .profile
    - .screenrc
    - .tmux.conf
    - .vim/plugin/vagrant.vim
    - .vim/snippets/javascript.snippets
    - .vimrc
    - .zshrc
