# you will need to log off to apply those changes
---
- name: user-dirs.dirs are setup
  copy:
    src: user-dirs.dirs
    dest: '{{ home_dir }}/.config/user-dirs.dirs'

- name: user-dirs.conf is setup
  copy:
    src: user-dirs.conf
    dest: '{{ home_dir }}/.config/user-dirs.conf'

- name: bookmarks are setup
  copy:
    src: bookmarks
    dest: '{{ home_dir }}/.config/gtk-3.0/bookmarks'
