---
- name: Atom rpm is present
  get_url:
    url: 'https://atom.io/download/rpm'
    dest: '{{ temp_dir }}/atom.x86_64.rpm'

- name: Atom is present
  dnf:
    name: '{{ temp_dir }}/atom.x86_64.rpm'
  become: yes

- name: Atom plugins are present
  shell: apm install {{ item }}
  with_items:
    - eclipse-keybindings
    - file-icons
    - file-types
    - highlight-selected
    - language-docker
    - language-dots
    - language-typescript-grammars-only
    - open-terminal-here
    - git-status
    - dbclick-tree-view
    - language-ansible
  tags: atom_plugins
