---
- include: kubectl_installer.yml
  tags:
  - kubernetes
  - kubectl

- include: minikube_installer.yml
  tags:
  - kubernetes
  - minikube

- include: kops_installer.yml
  tags:
  - kubernetes
  - kops
