---
- name: Chrome repo is added
  copy: 
    src: google-chrome.repo
    dest: /etc/yum.repos.d/
  become: yes

- name: Chrome signing key is imported
    rpm_key: 
      key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
      state: present

- name: Chrome is installed
  dnf: 
    name: google-chrome-stable
  become: yes
