---
- name: get latest terraform version id
  uri:
    url: 'https://checkpoint-api.hashicorp.com/v1/check/terraform'
    method: GET
    status_code: 200
    timeout: 10
  register: release

- set_fact:
    version: "{{ release.json | json_query('current_version') }}"

- name: terraform is present
  get_url:
    url: 'https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip'
    dest: '/tmp/terraform.zip'

- name: terraform is unzipped
  unarchive:
    src: '/tmp/terraform.zip'
    dest: '/tmp'
    creates: '/tmp/terraform'
    remote_src: True

- name: terraform binary is in path
  copy:
    src: '/tmp/terraform'
    dest: '/usr/local/bin/terraform'
  become: yes

- name: terraform is executable
  file:
    path: '/usr/local/bin/terraform'
    mode: 0755
  become: yes
