---
# https://yarnpkg.com/lang/en/docs/install/#centos--fedora--rhel
- name: Yarn repo is present
  copy:
    src: yarn.repo
    dest: "/etc/yum.repos.d/yarn.repo"
  become: yes

- name: Yarn is present
  dnf:
    name: yarn
    state: latest
  become: yes
