---
# This playbook installs webstorm IDE
# unfortunately there're no debian/ubuntu packages so
# we download zip and unarchive it
# in order to update your current installation you have to remove it manually
# After update you'll probably have to run application manually from
# ./bin/webstorm.sh and re - generate desktopr entry / cmd - launcher (Tools
# -> Create Desktop Entry) and re - import settings from ~/.WstormICXXX
# directory

- name: Check if there is any old installation
  stat: path="{{ local_soft_dir }}/webstorm/{{ software.webstorm.version }}"
  register: webstorm_state

- block:
  - name: Download webstorm tar
    get_url: >
      dest={{ temp_dir }}/{{ software.webstorm.version }}.tar.gz
      url="https://download.jetbrains.com/webstorm/{{ software.webstorm.version }}.tar.gz"

  - name: Create webstorm folder
    file: >
      path={{ local_soft_dir }}/webstorm/{{ software.webstorm.version }}
      state=directory

  - name: Extract archive
    unarchive: >
      src={{ temp_dir }}/{{ software.webstorm.version }}.tar.gz
      dest={{ local_soft_dir }}/webstorm/{{ software.webstorm.version }}/

  when: webstorm_state.stat.exists == false
