---
- name: unzip is present [fedora]
  dnf:
    name: unzip
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'

- name: unzip is present [mac]
  homebrew:
    name: unzip
    state: latest
  when: ansible_os_family == 'Darwin'
