---
# https://github.com/gnunn1/tilix
- name: tilix repo is added
  copy:
    src: heikoada-terminix.repo
    dest: /etc/yum.repos.d/heikoada-terminix.repo
  become: yes

- name: tilix is present
  dnf:
    name: tilix
    state: latest
  become: yes

- name: open-tilix-here plugin is present
  dnf:
    name: tilix-nautilus
    state: latest
  become: yes

- name: tilix custom configuration file is present
  copy:
    src: tilix.dconf
    dest: /tmp/tilix.dconf

- name: tilix custom configuration is loaded
  shell: dconf load /com/gexperts/Tilix/ < /tmp/tilix.dconf