---
# https://github.com/gnunn1/tilix
- name: tilix is present
  dnf:
    name: tilix
    state: latest
  become: yes

- name: open-tilix-here plugin is present
  dnf:
    name: tilix-nautilus
    state: latest
  become: yes

- name: tilix custom configuration file is present
  copy:
    src: tilix.dconf
    dest: /tmp/tilix.dconf

# dump profiles configs:
# dconf dump /com/gexperts/Tilix/ > roles/tilix/files/tilix.dconf
- name: tilix custom configuration is loaded
  shell: dconf load /com/gexperts/Tilix/ < /tmp/tilix.dconf
