---
# gsettings list-recursively | /usr/bin/grep "org.gnome.desktop.wm.keybindings" | cut -d' ' -f2- | sort
- name: remove unused keybindings/shortcuts part1
  shell: gsettings set org.gnome.desktop.wm.keybindings {{ item }}
  with_items:
    - activate-window-menu []
    - always-on-top []
    - begin-move []
    - begin-resize []
    - close "['<Alt>F4']"
    - cycle-group []
    - cycle-group-backward []
    - cycle-panels []
    - cycle-panels-backward []
    - cycle-windows []
    - cycle-windows-backward []
    - lower []
    - maximize []
    - maximize-horizontally []
    - maximize-vertically []
    - minimize []
    - move-to-center []
    - move-to-corner-ne []
    - move-to-corner-nw []
    - move-to-corner-se []
    - move-to-corner-sw []
    - move-to-monitor-down []
    - move-to-monitor-left []
    - move-to-monitor-right []
    - move-to-monitor-up []
    - move-to-side-e []
    - move-to-side-n []
    - move-to-side-s []
    - move-to-side-w []
    - move-to-workspace-1 []
    - move-to-workspace-2 []
    - move-to-workspace-3 []
    - move-to-workspace-4 []
    - move-to-workspace-5 []
    - move-to-workspace-6 []
    - move-to-workspace-7 []
    - move-to-workspace-8 []
    - move-to-workspace-9 []
    - move-to-workspace-10 []
    - move-to-workspace-11 []
    - move-to-workspace-12 []
    - move-to-workspace-down []
    - move-to-workspace-last []
    - move-to-workspace-left []
    - move-to-workspace-right []
    - move-to-workspace-up []
    - panel-main-menu []
    - panel-run-dialog []
    - raise []
    - raise-or-lower []
    - set-spew-mark []
    - show-desktop []
    - switch-applications-backward "['<Shift><Super>Tab']"
    - switch-applications "['<Super>Tab']"
    - switch-group-backward "['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']"
    - switch-group "['<Super>Above_Tab', '<Alt>Above_Tab']"
    - switch-input-source []
    - switch-input-source-backward []
    - switch-panels-backward "['<Shift><Control><Alt>Tab']"
    - switch-panels "['<Control><Alt>Tab']"
    - switch-to-workspace-1 "['<Super>1']"
    - switch-to-workspace-2 "['<Super>2']"
    - switch-to-workspace-3 "['<Super>3']"
    - switch-to-workspace-4 "['<Super>4']"
    - switch-to-workspace-5 []
    - switch-to-workspace-6 []
    - switch-to-workspace-7 []
    - switch-to-workspace-8 []
    - switch-to-workspace-9 []
    - switch-to-workspace-10 []
    - switch-to-workspace-11 []
    - switch-to-workspace-12 []
    - switch-to-workspace-down []
    - switch-to-workspace-last []
    - switch-to-workspace-left []
    - switch-to-workspace-right []
    - switch-to-workspace-up []
    - switch-windows "['<Alt>Tab']"
    - switch-windows-backward "['<Shift><Alt>Tab']"
    - toggle-above []
    - toggle-fullscreen []
    - toggle-maximized "['<Super>Up']"
    - toggle-on-all-workspaces []
    - toggle-shaded []
    - unmaximize "['<Super>Down']"

# gsettings list-recursively | grep "org.gnome.shell.keybindings"
- name: remove unused shell keybindings/shortcuts
  shell: gsettings set org.gnome.shell.keybindings {{ item }}
  with_items:
    - switch-to-application-1 []
    - switch-to-application-2 []
    - switch-to-application-3 []
    - switch-to-application-4 []
    - switch-to-application-5 []
    - switch-to-application-6 []
    - switch-to-application-7 []
    - switch-to-application-8 []
    - toggle-overview "['<Alt>space']"

# gsettings list-recursively | grep media-keys
- name: set media-keys keybindings/shortcuts
  shell: gsettings set org.gnome.settings-daemon.plugins.media-keys {{ item }}
  with_items:
    - home "['<Super>e']"
    - help []
    - search []
    - calculator []
    - www []
    - email []
    - decrease-text-size []
    - on-screen-keyboard []
    - increase-text-size []
    - toggle-contrast []

- name: prepare tilix shortcut
  shell: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/{{ item.key }} "{{ item.value }}"
  with_items:
    - { key: name, value: "'tilix'"}
    - { key: binding, value: "'<Primary><Alt>t'"}
    - { key: command, value: "'tilix'"}

- name: prepare jetbrains-toolbox shortcut
  shell: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/{{ item.key }} "{{ item.value }}"
  with_items:
    - { key: name, value: "'jetbrains-toolbox'"}
    - { key: binding, value: "'<Primary><Alt><Shift>k'"}
    - { key: command, value: "'jetbrains-toolbox'"}


- name: prepare flameshot shortcut
  shell: dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/{{ item.key }} "{{ item.value }}"
  with_items:
    - { key: name, value: "'flameshot'"}
    - { key: binding, value: "'<Primary><Alt><Shift>f'"}
    - { key: command, value: "'flameshot gui'"}

- name: set custom shortcut
  shell: >-
    dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings \
      "[ \
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', \
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', \
        '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/'] \
      "
