---
# https://github.com/phw/peek gif recorder
- block:
  - name: Install peek dependencies
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - libsdl1.2debian
      - ffmpeg
      - libavdevice-ffmpeg56

  - name: Install peek
    apt:
      deb: "{{ software.peek.url }}"

  become: yes
