---
# https://github.com/phw/peek

- name: Peek repo is present
  copy:
    src: 'home:Bajoja.repo'
    dest: '/etc/yum.repos.d/home:Bajoja.repo'
  become: yes

- name: Peek is present
  dnf:
    name: peek
    state: latest
  become: yes

