---
- name: gogland is present
  include_role:
    name: generic_jetbrains
  vars:
    software_name: 'goland'
    software_version: '{{ software.gogland.version }}'
    software_url: 'https://download.jetbrains.com/go/{{ software.gogland.version }}.tar.gz'
