---
- name: get latest release number
  uri:
    url: "https://api.github.com/repos/docker/compose/releases/latest"
    method: GET
    status_code: 200
    timeout: 10
  register: releases

- set_fact:
    binary_url: "{{ releases.json | json_query('assets[?name==`docker-compose-Linux-x86_64`].browser_download_url | [0]') }}"

- name: Docker Compose is present
  get_url:
    url: '{{ binary_url }}'
    dest: '/usr/local/bin/docker-compose'
  become: yes

- name: Docker Compose permissions are set
  file:
    path: '/usr/local/bin/docker-compose'
    mode: 0755
  become: yes
