---
# https://github.com/kubernetes/kops
- name: Kops (Kubernetes Operations) is present
  get_url:
    url: "{{ software.kubernetes.kops.url }}"
    dest: /usr/local/bin/kops
  become: yes

- name: Kops permissions are set
  file:
    path: /usr/local/bin/kops
    mode: 0755
  become: yes