---
# https://github.com/kubernetes/minikube
- name: Minikube is present
  get_url:
    url: "{{ software.kubernetes.minikube.url }}"
    dest: /usr/local/bin/minikube
  become: yes

- name: Minikube permissions are set
  file:
    path: /usr/local/bin/minikube
    mode: 0755
  become: yes

