---
# https://docs.docker.com/engine/installation/linux/fedora/#/install-using-the-repository
- name: Docker is present
  dnf:
    name: docker
  become: yes

- name: Docker group is present
  group:
    name: docker
    state: present
  become: yes

- name: My user is in the docker group
  shell: usermod -a -G docker {{ user }}
  become: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted
  become: yes

- name: Docker service is started
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes
