---
- name: docker-ce repo is added
  get_url:
    url: 'https://download.docker.com/linux/fedora/docker-ce.repo'
    dest: '/etc/yum.repos.d/docker-ce.repo'
  become: yes

- name: dnf-plugins-core is present
  dnf:
    name: dnf-plugins-core
    state: present
  become: yes

- name: containerd.io is present
  dnf:
    name: containerd.io
    state: present
  become: yes

- name: docker-ce-cli is present
  dnf:
    name: docker-ce-cli
    state: present
  become: yes

- name: docker-ce is present
  dnf:
    name: docker-ce
    state: present
  register: docker_installation
  become: yes

- name: restart docker service if installation changed
  service:
    name: docker
    state: restarted
  when: docker_installation.changed == true
  become: yes

- name: docker service is started
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes
