---
- name: Docker is present
  dnf:
    name: '{{ docker.dnf.version }}'
    state: present
  register: docker_installation
  become: yes

- name: Restart docker if installation changed
  service:
    name: docker
    state: restarted
  when: docker_installation.changed == true
  become: yes

- name: Docker group is present
  group:
    name: docker
    state: present
  become: yes

- name: Current user is in the docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes

- name: Docker service is started
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes