---
- name: Docker is present
  dnf:
    name: docker
    state: latest
  notify: Restart docker
  become: yes

- name: Docker group is present
  group:
    name: docker
    state: present
  become: yes

- name: Current user is in the docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes

- name: Docker service is started
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes