---
- name: Docker is present
  dnf:
    name: docker
    state: latest
  register: docker_is_present
  become: yes

- name: Docker group is present
  group:
    name: docker
    state: present
  become: yes

- name: Current user is in the docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes

- name: Restart Docker service if docker was changed
  service:
    name: docker
    state: restarted
  when: docker_is_present.changed == True
  become: yes

- name: Docker service is started
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started
  become: yes
