---
- block:
  - name: Update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install APT and CA certs packages
    apt: >
      name={{ item }}
      state=latest
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add GPG Key
    apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D
      state: present

  - name: Add docker repository and update apt cache
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
      update_cache: yes
      state: present

  - name: Install the linux-image-extra kernel packages
    apt: >
      name={{ item }}
      state=latest
    with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual

  - name: Install docker
    apt:
      name: docker-engine
      state: latest
      force: yes

  - name: Start docker service
    service:
      name: docker
      state: started

  - name: Add user to docker group
    command: usermod -aG docker {{ user }}

  become: yes
