---
- name: vim is installed
  dnf:
    name: vim-enhanced
    state: latest
  become: yes
  when: ansible_os_family == 'RedHat'

- name: vundle repo is cloned to vim bundle directory
  git: 
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    accept_hostkey: yes
    update: yes
    dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"

- name: Vim plugins are installed
  shell: vim +PluginInstall +qall
