---
- name: Install Vim
  apt: >
    name=vim
    state=latest

- name: Clone Vundle repo
  git: >
    repo=https://github.com/VundleVim/Vundle.vim.git
    accept_hostkey=yes
    update=yes
    dest={{ home_dir }}/.vim/bundle/Vundle.vim

- name: Install Vim plugins
  shell: vim +PluginInstall +qall
