---
- name: gimp is present
  dnf:
    name: gimp
    state: latest
  become: yes

- name: set gimp home path
  set_fact:
    gimp_home: '{{ home_dir }}/.gimp-2.8'

- name: backup existing gimp home
  synchronize:
    src: '{{ gimp_home }}/'
    dest: '{{ gimp_home}}.backup.{{ ansible_date_time.iso8601_micro }}'

- name: clone doctormo/GimpPs repo
  git:
    repo: 'https://github.com/doctormo/GimpPs.git'
    dest: '{{ temp_dir }}/GimpPs'
    depth: 1

- name: override gimp home directory with doctormo/GimpPs repo
  synchronize:
    src: '{{ temp_dir }}/GimpPs/'
    dest: '{{ gimp_home }}'